In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [4]:
ds = pd.read_csv('./Train.csv')
ds.shape

(7888, 20)

In [7]:
ds.head()

,FarmID,category,Crop,State,District,Sub-District,SDate,HDate,CropCoveredArea,CHeight,CNext,CLast,CTransp,IrriType,IrriSource,IrriCount,WaterCov,ExpYield,Season,geometry
0,1326576,Healthy,Paddy,Telangana,Medak,Kulcharam,2023-11-25 0:00:00,2024-04-14 0:00:00,97,54,Pea,Lentil,Transplanting,Flood,Groundwater,4,87,17,Rabi,POLYGON ((78.18143246076087 17.978884603571068...
1,1326577,Healthy,Paddy,Telangana,Medak,Kulcharam,2023-11-13 0:00:00,2024-04-26 0:00:00,82,58,Pea,Lentil,Transplanting,Flood,Canal,5,94,15,Rabi,POLYGON ((78.17545177547453 17.981074445477304...
2,1326578,Healthy,Paddy,Telangana,Medak,Kulcharam,2023-12-19 0:00:00,2024-04-28 0:00:00,92,91,Pea,Lentil,Transplanting,Flood,Canal,3,99,20,Rabi,POLYGON ((78.16914224770792 17.976212849967755...
3,1331836,Diseased,Paddy,Telangana,Medak,Kulcharam,2023-02-11 0:00:00,2024-11-04 0:00:00,91,52,Pea,Lentil,Transplanting,Flood,Canal,5,92,16,Rabi,POLYGON ((78.16889103841902 17.974608186550842...
4,1326579,Diseased,Paddy,Telangana,Medak,Kulcharam,2023-12-12 0:00:00,2024-05-19 0:00:00,94,55,Pea,Lentil,Transplanting,Flood,Canal,5,97,20,Rabi,POLYGON ((78.17264452998072 17.969251496349454...

In [13]:
cols = ds.columns
for col in cols:
    print(col)
    print(ds[col].value_counts())
    print('*'*64)

FarmID
FarmID
1326576    1
1318872    1
1318963    1
1318923    1
1318877    1
          ..
1332020    1
761542     1
1329634    1
1329633    1
1330504    1
Name: count, Length: 7888, dtype: int64
****************************************************************
category
category
Healthy     6506
Pests        485
Diseased     474
Stressed     423
Name: count, dtype: int64
****************************************************************
Crop
Crop
Paddy          2268
Cotton         1692
Maize          1384
Bengal Gram     938
Groundnut       768
Chillies        614
Red Gram        224
Name: count, dtype: int64
****************************************************************
State
State
Telangana    7888
Name: count, dtype: int64
****************************************************************
District
District
Adilabad        1770
Nalgonda        1386
Mahabubabad     1314
Nirmal          1244
Medak           1210
Mahabubnagar     655
Narayanpet       203
Nagarkurnool      47
Warangal          20
Siddipet          13
Vikarabad         11
Kamareddy          7
Wanaparthy         6
Khammam            2
Name: count, dtype: int64
****************************************************************
Sub-District
Sub-District
Utnur            470
Inderavelly      320
Havelighanpur    305
Gudur            270
Bhainsa          266
                ...
Devarkadra         3
Narsapur           2
Singareni          1
Pembi              1
Khammam_Rural      1
Name: count, Length: 116, dtype: int64
****************************************************************
SDate
SDate
2023-11-19 0:00:00    108
2023-11-23 0:00:00    102
2023-11-11 0:00:00     95
2023-11-20 0:00:00     94
2023-11-28 0:00:00     94
                     ...
2024-04-18 0:00:00      1
2023-01-31 0:00:00      1
2024-01-04 0:00:00      1
2024-02-13 0:00:00      1
2023-09-17 0:00:00      1
Name: count, Length: 419, dtype: int64
****************************************************************
HDate
HDate
2024-01-04 0:00:00    80
2024-02-04 0:00:00    73
2024-01-03 0:00:00    72
2024-04-20 0:00:00    67
2024-04-23 0:00:00    67
                      ..
2024-07-24 0:00:00     1
2023-03-23 0:00:00     1
2024-10-21 0:00:00     1
2024-08-07 0:00:00     1
2023-04-12 0:00:00     1
Name: count, Length: 476, dtype: int64
****************************************************************
CropCoveredArea
CropCoveredArea
95    557
80    221
88    209
85    203
89    199
     ...
47     21
45     19
48     16
43     14
42     13
Name: count, Length: 61, dtype: int64
****************************************************************
CHeight
CHeight
74     463
83     105
67     104
39     102
72      97
      ...
186      4
173      4
170      4
189      4
177      3
Name: count, Length: 231, dtype: int64
****************************************************************
CNext
CNext
Pea        1355
Wheat      1326
Maize      1212
Sorghum     953
Lentil      913
Soybean     665
Mustard     445
Rice        405
Onion       321
Tomato      293
Name: count, dtype: int64
****************************************************************
CLast
CLast
Lentil     1350
Maize      1258
Wheat      1235
Sorghum     953
Pea         918
Soybean     704
Mustard     493
Rice        363
Tomato      321
Onion       293
Name: count, dtype: int64
****************************************************************
CTransp
CTransp
Transplanting    2268
Drilling         1908
Broadcasting     1879
Seed Drilling    1833
Name: count, dtype: int64
****************************************************************
IrriType
IrriType
Drip         2871
Sprinkler    2282
Flood        2268
Surface       467
Name: count, dtype: int64
****************************************************************
IrriSource
IrriSource
Groundwater    3338
Canal          3189
Rainfed        1251
Well             57
Tubewell         53
Name: count, dtype: int64
****************************************************************
IrriCount
IrriCount
4    1932
3    1860
2    1453
5    1288
6     780
1     575
Name: count, dtype: int64
****************************************************************
WaterCov
WaterCov
40    248
48    218
50    209
47    209
43    205
     ...
22     71
35     66
28     65
29     61
20     60
Name: count, Length: 62, dtype: int64
****************************************************************
ExpYield
ExpYield
10    689
17    656
11    648
12    640
15    601
20    524
13    381
14    376
9     320
8     312
19    300
24    277
23    273
16    259
21    255
25    253
18    251
22    226
7     101
5      93
6      87
29     86
28     83
27     77
26     68
30     52
Name: count, dtype: int64
****************************************************************
Season
Season
Rabi      6180
Kharif    1708
Name: count, dtype: int64
****************************************************************
geometry
geometry
POLYGON ((78.18143246076087 17.978884603571068, 78.18149324901445 17.97898640558611, 78.18175397935514 17.978865561467536, 78.18166316316905 17.978728604799823, 78.18143246076087 17.978884603571068))                                                                                                                                                                                                                                      1
POLYGON ((78.73213005977762 19.430868922717423, 78.73188368976116 19.430909876281866, 78.7316557019949 19.43095382528397, 78.73132941795606 19.431033130785284, 78.73103577643633 19.431112863659834, 78.73108565566899 19.43130035136776, 78.73175896704197 19.431130253532448, 78.73208314318683 19.431069848117225, 78.73216167748015 19.431051489451256, 78.73213950544596 19.430946236967912, 78.73213005977762 19.430868922717423))    1
POLYGON ((78.47772031569752 17.96373066031036, 78.4777420386672 17.96381855555728, 78.4778905659914 17.963755407028344, 78.4778311776789 17.96355348835882, 78.47774621802962 17.963316222996813, 78.47764882526094 17.96335766672817, 78.47772031569752 17.96373066031036))                                                                                                                                                                 1
POLYGON ((78.458816036582 17.990055772612546, 78.4590969979763 17.99002165196537, 78.45897149701061 17.989520086718326, 78.45866330992013 17.989568384695193, 78.458816036582 17.990055772612546))                                                                                                                                                                                                                                           1
POLYGON ((78.73121276944643 19.431700854857024, 78.73130648468805 19.432048756644345, 78.73226959258318 19.43181161889346, 78.73222052923627 19.431455654704333, 78.73121276944643 19.431700854857024))                                                                                                                                                                                                                                      1
                                                                                                                                                                                                                                                                                                                                                                                                                                            ..
POLYGON ((77.94991564186205 16.812695300453186, 77.94993739947978 16.812860993080278, 77.95028384769995 16.81275555231747, 77.9502235958355 16.81261831195974, 77.94991564186205 16.812695300453186))                                                                                                                                                                                                                                        1
POLYGON ((77.93565582475003 16.812649902346948, 77.93571597201054 16.812846034718063, 77.93589902889005 16.812772811966113, 77.93603239890251 16.81272051000053, 77.93615269342337 16.81266820803495, 77.93611608204736 16.812506071941584, 77.93579965515539 16.812589755086606, 77.93573950789511 16.812613290971115, 77.93565582475003 16.812649902346948))                                                                               1
POLYGON ((77.96085242639163 16.801100096938683, 77.96092205076826 16.801358242704225, 77.96118126767811 16.80128219146212, 77.96111914131126 16.801025116840833, 77.96085242639163 16.801100096938683))                                                                                                                                                                                                                                      1
POLYGON ((77.99010196174237 16.79658294771923, 77.99027937000983 16.796705125110975, 77.99034631652569 16.79672018807713, 77.99045343095133 16.7965946633596, 77.99057728200586 16.79650930655174, 77.99054380874793 16.79643566538408, 77.99047853589485 16.796345287587656, 77.99044338897392 16.796285035723145, 77.99034129553712 16.796283362060365, 77.99016723459545 16.79645909666482, 77.99010196174237 16.79658294771923))         1
POLYGON ((80.11488574279815 17.37210773770654, 80.11505125431205 17.372079454093402, 80.11507639530151 17.37192651307423, 80.11511201170323 17.371715957287556, 80.11511096416201 17.371576634304336, 80.11489307558675 17.371642629401652, 80.11490878870515 17.371779857302418, 80.11489831329288 17.371934893404045, 80.11488574279815 17.37210773770654))                                                                                1
Name: count, Length: 7888, dtype: int64
****************************************************************

In [17]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7888 entries, 0 to 7887
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FarmID           7888 non-null   int64
 1   category         7888 non-null   object
 2   Crop             7888 non-null   object
 3   State            7888 non-null   object
 4   District         7888 non-null   object
 5   Sub-District     7888 non-null   object
 6   SDate            7888 non-null   object
 7   HDate            7888 non-null   object
 8   CropCoveredArea  7888 non-null   int64
 9   CHeight          7888 non-null   int64
 10  CNext            7888 non-null   object
 11  CLast            7888 non-null   object
 12  CTransp          7888 non-null   object
 13  IrriType         7888 non-null   object
 14  IrriSource       7888 non-null   object
 15  IrriCount        7888 non-null   int64
 16  WaterCov         7888 non-null   int64
 17  ExpYield         7888 non-null   int64
 18  Season           7888 non-null   object
 19  geometry         7888 non-null   object
dtypes: int64(6), object(14)
memory usage: 1.2+ MB

In [18]:
ds_test = pd.read_csv('./Test.csv')
ds_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2718 entries, 0 to 2717
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FarmID           2718 non-null   int64
 1   Crop             2718 non-null   object
 2   State            2718 non-null   object
 3   District         2718 non-null   object
 4   Sub-District     2718 non-null   object
 5   SDate            2718 non-null   object
 6   HDate            2718 non-null   object
 7   CropCoveredArea  2718 non-null   int64
 8   CHeight          2718 non-null   int64
 9   CNext            2718 non-null   object
 10  CLast            2718 non-null   object
 11  CTransp          2718 non-null   object
 12  IrriType         2718 non-null   object
 13  IrriSource       2718 non-null   object
 14  IrriCount        2718 non-null   int64
 15  WaterCov         2718 non-null   int64
 16  ExpYield         2718 non-null   int64
 17  Season           2718 non-null   object
 18  geometry         2718 non-null   object
dtypes: int64(6), object(13)
memory usage: 403.6+ KB

In [19]:
X = ds.drop(['category'], axis=1)
y = ds['category']

In [20]:
X.shape

(7888, 19)

In [21]:
ds_test.shape

(2718, 19)

In [22]:
X.columns

Index(['FarmID', 'Crop', 'State', 'District', 'Sub-District', 'SDate', 'HDate',
       'CropCoveredArea', 'CHeight', 'CNext', 'CLast', 'CTransp', 'IrriType',
       'IrriSource', 'IrriCount', 'WaterCov', 'ExpYield', 'Season',
       'geometry'],
      dtype='object')

In [25]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7888 entries, 0 to 7887
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FarmID           7888 non-null   int64
 1   Crop             7888 non-null   object
 2   State            7888 non-null   object
 3   District         7888 non-null   object
 4   Sub-District     7888 non-null   object
 5   SDate            7888 non-null   object
 6   HDate            7888 non-null   object
 7   CropCoveredArea  7888 non-null   int64
 8   CHeight          7888 non-null   int64
 9   CNext            7888 non-null   object
 10  CLast            7888 non-null   object
 11  CTransp          7888 non-null   object
 12  IrriType         7888 non-null   object
 13  IrriSource       7888 non-null   object
 14  IrriCount        7888 non-null   int64
 15  WaterCov         7888 non-null   int64
 16  ExpYield         7888 non-null   int64
 17  Season           7888 non-null   object
 18  geometry         7888 non-null   object
dtypes: int64(6), object(13)
memory usage: 1.1+ MB

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)